services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myServer
    depends_on:
      - mysql_base
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_base:${MYSQL_PORT}/${MYSQL_NAME}
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8080:8080

  mysql_base:
    image: mysql:8.0
    container_name: mysql_container
    #    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - /db/init.sql:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network